{% set name = "ultralytics" %}
{% set version = "8.3.193" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ultralytics-{{ version }}.tar.gz
  sha256: bec0001205b3298b099c94ec4988d41b225c07e7af57fb02b612eb1546ce3e6a

build:
  entry_points:
    - yolo = ultralytics.cfg:entrypoint
    - ultralytics = ultralytics.cfg:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=70.0.0
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.3.0
    - numpy >=1.22.2
    - opencv >=4.6.0
    - pillow >=7.1.2
    - pyyaml >=5.3.1
    - requests >=2.23.0
    - scipy >=1.4.1
    # - pytorch >=1.7.0
    # - torchvision >=0.8.1
    - polars
    - seaborn >=0.11.0
    - psutil
    - py-cpuinfo

test:
  source_files:
    - tests
  imports:
    - ultralytics
  commands:
    # coremltools>=7.0 requires pip install as latest conda coremltools==4.1
    # ultralytics-thop requires pip install as not available in conda
    - pip install ultralytics-thop>=2.0.0
    - pip check
    - yolo checks
    - ultralytics version
    - ls tests
    - pytest tests/test_cli.py
    # - pytest tests/
  requires:
    - pip
    - git
    - pytest
    - pytorch
    - torchvision
    # - openvino  # note compatibility issue with numpy>2.0
    # - coremltools
    # - thop
    # - hub-sdk
    - python {{ python_min }}

about:
  home: https://ultralytics.com
  summary: Ultralytics YOLO for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
  doc_url: https://docs.ultralytics.com
  dev_url: https://github.com/ultralytics/ultralytics
  license: AGPL-3.0-only
  license_file: LICENSE
  description: |
    ![Ultralytics YOLO banner](https://raw.githubusercontent.com/ultralytics/assets/main/yolov8/banner-yolov8.png)

    [中文](https://docs.ultralytics.com/zh/) | [한국어](https://docs.ultralytics.com/ko/) | [日本語](https://docs.ultralytics.com/ja/) | [Русский](https://docs.ultralytics.com/ru/) | [Deutsch](https://docs.ultralytics.com/de/) | [Français](https://docs.ultralytics.com/fr/) | [Español](https://docs.ultralytics.com/es/) | [Português](https://docs.ultralytics.com/pt/) | [Türkçe](https://docs.ultralytics.com/tr/) | [Tiếng Việt](https://docs.ultralytics.com/vi/) | [हिन्दी](https://docs.ultralytics.com/hi/) | [العربية](https://docs.ultralytics.com/ar/)

    [Ultralytics](https://www.ultralytics.com/) [YOLO](https://github.com/ultralytics/ultralytics) is a cutting-edge, state-of-the-art (SOTA) model that builds upon the success of previous YOLO versions and introduces new features and improvements to further boost performance and flexibility. YOLO is designed to be fast, accurate, and easy to use, making it an excellent choice for a wide range of object detection and tracking, instance segmentation, image classification and pose estimation tasks.

    We hope that the resources here will help you get the most out of YOLO. Please browse the Ultralytics <a href="https://docs.ultralytics.com/">Docs</a> for details, raise an issue on <a href="https://github.com/ultralytics/ultralytics/issues/new/choose">GitHub</a> for support, questions, or discussions, become a member of the Ultralytics <a href="https://discord.com/invite/ultralytics">Discord</a>, <a href="https://reddit.com/r/ultralytics">Reddit</a> and <a href="https://community.ultralytics.com/">Forums</a>!

    To request an Enterprise License please complete the form at [Ultralytics Licensing](https://www.ultralytics.com/license).

    ![Ultralytics YOLO performance comparison](https://raw.githubusercontent.com/ultralytics/assets/refs/heads/main/yolo/performance-comparison.png)

    YOLO [Detect](https://docs.ultralytics.com/tasks/detect), [Segment](https://docs.ultralytics.com/tasks/segment) and [Pose](https://docs.ultralytics.com/tasks/pose) models pretrained on the [COCO](https://docs.ultralytics.com/datasets/detect/coco) dataset are available, as well as YOLO [Classify](https://docs.ultralytics.com/tasks/classify) models pretrained on the [ImageNet](https://docs.ultralytics.com/datasets/classify/imagenet) dataset. [Track](https://docs.ultralytics.com/modes/track) mode is available for all Detect, Segment and Pose models. All [Models](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/models) download automatically from the latest Ultralytics [release](https://github.com/ultralytics/assets/releases) on first use.

extra:
  recipe-maintainers:
    - onuralpszr
    - UltralyticsAssistant
    - glenn-jocher
    - Laughing-q
    - pderrenger
