{% set name = "ultralytics" %}
{% set version = "8.0.184" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ultralytics-{{ version }}.tar.gz
  sha256: 21d2e2d8c20d25c4464930386c60f1515c343aa53bb2a499e0b44eee736de5c7

build:
  entry_points:
    - yolo = ultralytics.cfg:entrypoint
    - ultralytics = ultralytics.cfg:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install .
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.2.2
    - numpy >=1.22.2
    - opencv >=4.6.0
    - pillow >=7.1.2
    - pyyaml >=5.3.1
    - requests >=2.23.0
    - scipy >=1.4.1
    # - pytorch >=1.7.0
    # - torchvision >=0.8.1
    - tqdm >=4.64.0
    - pandas >=1.1.4
    - seaborn >=0.11.0
    - psutil
    - py-cpuinfo

test:
  source_files:
    - tests
    - setup.cfg
  imports:
    - ultralytics
  commands:
    - pip check
    - yolo checks
    - ultralytics version
    - pytest tests/test_cli.py tests/test_cuda.py tests/test_engine.py tests/test_python.py
  requires:
    - pip
    - git
    - pytest
    - pytorch
    - torchvision

about:
  home: https://ultralytics.com
  summary: Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
  doc_url: https://docs.ultralytics.com
  dev_url: https://github.com/ultralytics/ultralytics
  license: AGPL-3.0-only
  license_file: LICENSE
  description: |
    ![Ultralytics YOLOv8 banner](https://raw.githubusercontent.com/ultralytics/assets/main/yolov8/banner-yolov8.png)

    [Ultralytics](https://ultralytics.com) [YOLOv8](https://github.com/ultralytics/ultralytics) is a cutting-edge, state-of-the-art (SOTA) model that builds upon the success of previous YOLO versions and introduces new features and improvements to further boost performance and flexibility. YOLOv8 is designed to be fast, accurate, and easy to use, making it an excellent choice for a wide range of object detection and tracking, instance segmentation, image classification and pose estimation tasks.

    We hope that the resources here will help you get the most out of YOLOv8. Please browse the YOLOv8 <a href="https://docs.ultralytics.com/">Docs</a> for details, raise an issue on <a href="https://github.com/ultralytics/ultralytics/issues/new/choose">GitHub</a> for support, and join our <a href="https://ultralytics.com/discord">Discord</a> community for questions and discussions!

    To request an Enterprise License please complete the form at [Ultralytics Licensing](https://ultralytics.com/license).

    ![Ultralytics YOLOv8 comparison plots](https://raw.githubusercontent.com/ultralytics/assets/main/yolov8/yolo-comparison-plots.png)

    YOLOv8 [Detect](https://docs.ultralytics.com/tasks/detect), [Segment](https://docs.ultralytics.com/tasks/segment) and [Pose](https://docs.ultralytics.com/tasks/pose) models pretrained on the [COCO](https://docs.ultralytics.com/datasets/detect/coco) dataset are available, as well as YOLOv8 [Classify](https://docs.ultralytics.com/tasks/classify) models pretrained on the [ImageNet](https://docs.ultralytics.com/datasets/classify/imagenet) dataset. [Track](https://docs.ultralytics.com/modes/track) mode is available for all Detect, Segment and Pose models. All [Models](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/models) download automatically from the latest Ultralytics [release](https://github.com/ultralytics/assets/releases) on first use.

extra:
  recipe-maintainers:
    - glenn-jocher
    - AyushExel
    - Laughing-q
    - abraha2d
