{% set name = "ultralytics" %}
{% set version = "8.0.120" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ultralytics-{{ version }}.tar.gz
  sha256: d0f346ae9c43ee3f6dd8a5cd28ef3dc1c16590a1f604c5d83bb86321b32b57ac

build:
  entry_points:
    - yolo = ultralytics.yolo.cfg:entrypoint
    - ultralytics = ultralytics.yolo.cfg:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.2.2
    - opencv >=4.6.0
    - pillow >=7.1.2
    - pyyaml >=5.3.1
    - requests >=2.23.0
    - scipy >=1.4.1
    - pytorch >=1.7.0
    - torchvision >=0.8.1
    - tqdm >=4.64.0
    - pandas >=1.1.4
    - seaborn >=0.11.0
    - psutil
    - sentry-sdk

test:
  imports:
    - ultralytics
  commands:
    - pip check
    - yolo --help
    - ultralytics --help
  requires:
    - pip

about:
  home: https://github.com/ultralytics/ultralytics
  summary: Ultralytics YOLOv8
  dev_url: https://github.com/ultralytics/ultralytics
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - glenn-jocher
    - AyushExel
    - Laughing-q
    - abraha2d
